const STORAGE_KEY="routeTrackerData.v2";
const DEFAULTS={settings:{startTime:"08:30",dailyTarget:20,cycle:{visitsRequired:2,windowDays:21},targets:{East:35,North:35}},clusters:[],customers:[],visits:[],todayList:[],clusterProgress:{completed:{}}};
const byId=(id)=>document.getElementById(id);
const safeParse=(s)=>{try{return JSON.parse(s);}catch{return null;}};
const todayISO=()=>new Date().toISOString().slice(0,10);
const nowISO=()=>new Date().toISOString();
let state=(()=>{const raw=localStorage.getItem(STORAGE_KEY);const p=raw?safeParse(raw):null;return p?p:structuredClone(DEFAULTS);})();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll();}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',\"'\":'&#39;'}[m]));}
function computeCompliance(c){if(!c.existing)return{status:"prospect",label:"Prospect",dot:"gray"};const w=state.settings.cycle.windowDays,req=state.settings.cycle.visitsRequired;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-w);const recent=(c.visitHistory||[]).filter(v=>new Date(v.date)>=cutoff);const n=recent.length;if(n>=req)return{status:"compliant",label:"Compliant",dot:"green"};if(n===req-1)return{status:"due",label:"Due",dot:"amber"};return{status:"overdue",label:"Overdue",dot:"red"};}
function activeCountByRoute(route){const activeFromVisits=new Set(state.visits.filter(v=>v.outcome==="active"||v.outcome==="standing_order").map(v=>v.customerName));return state.customers.filter(c=>c.routeGroup===route&&(c.existing||activeFromVisits.has(c.name))).length;}
function routeGap(route){const target=state.settings.targets[route]??0;const actual=activeCountByRoute(route);return{target,actual,gap:actual-target};}
function periodRange(period){const d=new Date();const end=d.toISOString().slice(0,10);if(period==="week"){const day=d.getDay();const diff=(day===0?6:day-1);const s=new Date(d);s.setDate(d.getDate()-diff);return{start:s.toISOString().slice(0,10),end};}if(period==="month"){const s=new Date(d.getFullYear(),d.getMonth(),1);return{start:s.toISOString().slice(0,10),end};}if(period==="quarter"){const q=Math.floor(d.getMonth()/3);const s=new Date(d.getFullYear(),q*3,1);return{start:s.toISOString().slice(0,10),end};}const s=new Date(d.getFullYear(),0,1);return{start:s.toISOString().slice(0,10),end};}
function computePace(){const [h,m]=state.settings.startTime.split(":").map(Number);const start=new Date();start.setHours(h,m,0,0);const now=new Date();const minutes=Math.max(0,(now-start)/60000);const dayMinutes=8*60;const target=Number(state.settings.dailyTarget||20);const expected=Math.min(target,Math.round((minutes/dayMinutes)*target));const done=state.visits.filter(v=>v.date===todayISO()).length;const delta=done-expected;let label="🟡 On pace";if(delta>=3)label="🟢 Ahead";if(delta<=-3)label="🔴 Behind";return{label,done,expected,target};}
function currentCluster(){for(const c of (state.clusters||[])){const key=`${c.day}|${c.cluster}`;if(!state.clusterProgress.completed[key])return c;}return state.clusters?.[0]||null;}
function customersInCluster(cluster){if(!cluster)return[];const label=(cluster.cluster||"").toLowerCase();const reg=(cluster.region||"").toLowerCase();const labelWord=label.split("(")[0].trim();return state.customers.filter(c=>{const s=`${c.suburb} ${c.hub} ${c.region}`.toLowerCase();return (labelWord&&s.includes(labelWord))||(reg&&s.includes(reg));});}
function generateToday(){const cluster=currentCluster();const pool=customersInCluster(cluster);const scored=pool.map(c=>{const comp=computeCompliance(c);let score=0;if(c.existing)score+=100;if(comp.status==="overdue")score+=80;if(comp.status==="due")score+=50;if(!c.existing)score+=10;if(c.tier==="A")score+=30;if(c.tier==="B")score+=20;if(c.tier==="C")score+=10;return{c,score,comp};}).sort((a,b)=>b.score-a.score);state.todayList=scored.slice(0,Number(state.settings.dailyTarget||20)).map(x=>x.c.name);save();}
function setTab(tab){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tabpanel").forEach(p=>p.classList.toggle("active",p.id===`tab-${tab}`));}
function renderTop(){const pace=computePace();byId("paceStatus").textContent=pace.label;byId("paceSub").textContent=`Done ${pace.done}/${pace.target} • Expected ${pace.expected}`;const c=currentCluster();byId("todayCluster").textContent=c?c.cluster:"—";byId("todayClusterSub").textContent=c?`Day ${c.day} • ${c.region||""}`:"Import call cycle to begin";const e=routeGap("East"),n=routeGap("North");byId("targetsKpi").textContent=`East ${e.actual}/${e.target} • North ${n.actual}/${n.target}`;byId("targetsSub").textContent=`Gap East ${e.gap} • Gap North ${n.gap}`;}
function renderDatalist(){byId("customerDatalist").innerHTML=state.customers.map(c=>`<option value="${esc(c.name)}"></option>`).join("");}
function renderToday(){const el=byId("todayList");if(!state.todayList?.length){el.innerHTML=`<div class="item"><div class="muted">No list yet. Tap <strong>Generate</strong>.</div></div>`;return;}el.innerHTML=state.todayList.map((name,idx)=>{const c=state.customers.find(x=>x.name===name);const comp=c?computeCompliance(c):{label:"",dot:"gray"};const meta=c?`${c.routeGroup} • ${c.suburb||""} • Tier ${c.tier||"B"}`:"";return `<div class="item"><h4>${esc(name)} <span class="pill" style="margin-left:8px"><span class="dot ${comp.dot}"></span>${esc(comp.label)}</span></h4><div class="meta">${esc(meta)}</div><div class="actions"><button class="btn ghost small" data-act="up" data-idx="${idx}">Up</button><button class="btn ghost small" data-act="down" data-idx="${idx}">Down</button><button class="btn ghost small" data-act="remove" data-idx="${idx}">Remove</button><button class="btn small" data-act="log" data-name="${esc(name)}">Log Visit</button></div></div>`;}).join("");}
function renderCustomers(){const q=(byId("customerSearch").value||"").toLowerCase();const filter=byId("customerFilter").value;let list=state.customers;if(q)list=list.filter(c=>c.name.toLowerCase().includes(q));if(filter==="existing")list=list.filter(c=>c.existing);if(filter==="prospect")list=list.filter(c=>!c.existing);if(filter==="overdue")list=list.filter(c=>computeCompliance(c).status==="overdue");if(filter==="due")list=list.filter(c=>computeCompliance(c).status==="due");const el=byId("customerList");if(!list.length){el.innerHTML=`<div class="item"><div class="muted">No customers match.</div></div>`;return;}el.innerHTML=list.slice(0,300).map(c=>{const comp=computeCompliance(c);const tag=c.existing?`<span class="pill"><span class="dot yellow"></span>Existing</span>`:`<span class="pill"><span class="dot gray"></span>Prospect</span>`;const compPill=c.existing?`<span class="pill"><span class="dot ${comp.dot}"></span>${comp.label}</span>`:"";const last=(c.visitHistory?.[c.visitHistory.length-1]?.date)||"—";const meta=`${c.routeGroup} • ${c.suburb||""} • Last: ${last} • Tier ${c.tier||"B"}`;return `<div class="item"><h4>${esc(c.name)}</h4><div class="meta">${tag}${compPill}<span class="pill">${esc(meta)}</span></div><div class="meta" style="margin-top:8px"><span class="pill">Key Contact: ${esc(c.keyContact||"—")}</span><span class="pill">Next: ${esc(c.nextAction||"—")}</span></div><div class="actions"><button class="btn small" data-act="openCustomer" data-name="${esc(c.name)}">Open</button><button class="btn ghost small" data-act="addToday" data-name="${esc(c.name)}">Add to Today</button></div></div>`;}).join("");}
function renderClusters(){const el=byId("clusterList");if(!state.clusters?.length){el.innerHTML=`<div class="item"><div class="muted">No call cycle loaded yet. Import your customer file to preload clusters.</div></div>`;return;}const cur=currentCluster();el.innerHTML=state.clusters.slice(0,200).map(c=>{const key=`${c.day}|${c.cluster}`;const done=!!state.clusterProgress.completed[key];const isCur=cur&&(c.day===cur.day&&c.cluster===cur.cluster);return `<div class="item"><h4>${done?"✅":isCur?"▶":"•"} Day ${c.day}: ${esc(c.cluster)}</h4><div class="meta">${esc(c.region||"")} • ${done?"Completed":"Pending"}</div></div>`;}).join("");}
function renderRecent(){const el=byId("recentVisits");const recent=[...state.visits].slice(-10).reverse();if(!recent.length){el.innerHTML=`<div class="item"><div class="muted">No visits yet.</div></div>`;return;}el.innerHTML=recent.map(v=>`<div class="item"><h4>${esc(v.customerName)} <span class="pill">${esc(v.date)}</span></h4><div class="meta">${esc(v.routeGroup)} • ${esc(v.outcomeLabel)}</div><div class="muted" style="margin-top:8px">${esc(v.notes||"")}</div></div>`).join("");}
function renderReport(){const period=byId("reportPeriod").value;const route=byId("reportRoute").value;const {start,end}=periodRange(period);let visits=state.visits.filter(v=>v.date>=start&&v.date<=end);if(route!=="all")visits=visits.filter(v=>v.routeGroup===route);const calls=visits.length,dm=visits.filter(v=>v.outcome==="decision_maker").length,samples=visits.filter(v=>v.outcome==="sample").length,trials=visits.filter(v=>v.outcome==="trial").length,actives=visits.filter(v=>v.outcome==="active").length,standing=visits.filter(v=>v.outcome==="standing_order").length;const sr=calls?(((trials+actives+standing)/calls)*100).toFixed(1):"0.0";const e=routeGap("East"),n=routeGap("North");byId("reportSnapshot").innerHTML=`<div class="item"><h4>Period: ${esc(start)} → ${esc(end)} ${route!=="all"?"• "+esc(route):""}</h4><div class="meta"><span class="pill">Calls: ${calls}</span><span class="pill">Decision Makers: ${dm}</span><span class="pill">Samples: ${samples}</span><span class="pill">Trials: ${trials}</span><span class="pill">Actives: ${actives}</span><span class="pill">Standing Orders: ${standing}</span><span class="pill">Strike Rate: ${sr}%</span></div><div class="meta" style="margin-top:10px"><span class="pill">East Actives: ${e.actual}/${e.target} (Gap ${e.gap})</span><span class="pill">North Actives: ${n.actual}/${n.target} (Gap ${n.gap})</span></div></div>`;}
function renderAll(){renderTop();renderDatalist();renderToday();renderCustomers();renderClusters();renderRecent();renderReport();}
function saveVisit(){const name=byId("visitCustomer").value.trim();if(!name){alert("Choose a customer.");return;}const routeGroup=byId("visitRouteGroup").value;const outcome=byId("visitOutcome").value;const notes=byId("visitNotes").value.trim();const keyContact=byId("visitKeyContact").value.trim();const nextAction=byId("visitNextAction").value.trim();const labels={no_contact:"No contact",staff:"Spoke to staff",decision_maker:"Decision maker",sample:"Sample placed",trial:"Trial started",active:"Active confirmed",standing_order:"Standing order"};const visit={id:crypto.randomUUID(),date:todayISO(),ts:nowISO(),customerName:name,routeGroup,outcome,outcomeLabel:labels[outcome]||outcome,notes,gps:state._lastGps||null};state.visits.push(visit);state._lastGps=null;let c=state.customers.find(x=>x.name===name);if(!c){c={name,existing:false,routeGroup,region:"",suburb:"",hub:"",address:"",notes:"",tier:"B",keyContact:"",nextAction:"",visitHistory:[]};state.customers.push(c);}c.routeGroup=routeGroup||c.routeGroup;if(keyContact)c.keyContact=keyContact;if(nextAction)c.nextAction=nextAction;c.visitHistory=c.visitHistory||[];c.visitHistory.push({date:visit.date,outcome:visit.outcome,notes:visit.notes,gps:visit.gps});byId("visitNotes").value="";byId("visitKeyContact").value="";byId("visitNextAction").value="";save();}
function gpsCheckIn(){if(!navigator.geolocation){alert("GPS not supported.");return;}navigator.geolocation.getCurrentPosition(pos=>{state._lastGps={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,ts:nowISO()};save();alert("GPS captured for next saved visit.");},err=>alert("GPS error: "+err.message),{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
function exportData(){const stamp=todayISO();const filename=`route-tracker-backup-${stamp}.json`;const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function importData(file){const reader=new FileReader();reader.onload=()=>{const obj=safeParse(reader.result);if(!obj){alert("Invalid JSON.");return;}if(obj.customers&&obj.clusters&&obj.targets){state.customers=obj.customers;state.clusters=obj.clusters;state.settings.targets.East=obj.targets.East?.activeTarget??state.settings.targets.East;state.settings.targets.North=obj.targets.North?.activeTarget??state.settings.targets.North;state.visits=obj.visits||[];state.todayList=[];state.clusterProgress=state.clusterProgress||{completed:{}};save();alert("Customer + call cycle loaded.");return;}state=obj;save();alert("Backup imported.");};reader.readAsText(file);}
function markClusterDone(){const c=currentCluster();if(!c){alert("No cluster found.");return;}const key=`${c.day}|${c.cluster}`;state.clusterProgress.completed[key]={ts:nowISO()};save();}
function exportKpi(){const period=byId("reportPeriod").value;const route=byId("reportRoute").value;const {start,end}=periodRange(period);let visits=state.visits.filter(v=>v.date>=start&&v.date<=end);if(route!=="all")visits=visits.filter(v=>v.routeGroup===route);const calls=visits.length,dm=visits.filter(v=>v.outcome==="decision_maker").length,samples=visits.filter(v=>v.outcome==="sample").length,trials=visits.filter(v=>v.outcome==="trial").length,actives=visits.filter(v=>v.outcome==="active").length,standing=visits.filter(v=>v.outcome==="standing_order").length;const sr=calls?(((trials+actives+standing)/calls)*100).toFixed(1):"0.0";const e=routeGap("East"),n=routeGap("North");const text=`KPI REPORT\nPeriod: ${start} to ${end}\nRoute: ${route}\n\nACTIVITY\nCalls: ${calls}\nDecision Makers: ${dm}\nSamples: ${samples}\nTrials: ${trials}\nNew Actives: ${actives}\nStanding Orders: ${standing}\nStrike Rate: ${sr}%\n\nTARGETS (Actives)\nEast: ${e.actual}/${e.target} (Gap ${e.gap})\nNorth: ${n.actual}/${n.target} (Gap ${n.gap})\n`;const stamp=todayISO();const filename=`kpi-report-${period}-${stamp}.txt`;const blob=new Blob([text],{type:"text/plain"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function saveSettings(){state.settings.startTime=byId("startTime").value.trim()||"08:30";state.settings.dailyTarget=Number(byId("dailyTarget").value||20);state.settings.targets.East=Number(byId("targetEast").value||35);state.settings.targets.North=Number(byId("targetNorth").value||35);save();alert("Settings saved.");}
function factoryReset(){if(!confirm("This deletes ALL data on this device. Continue?"))return;state=structuredClone(DEFAULTS);save();}
document.addEventListener("click",(e)=>{const tabBtn=e.target.closest(".tab");if(tabBtn)return setTab(tabBtn.dataset.tab);const t=e.target; if(t.id==="btnGenerateToday")return generateToday(); if(t.id==="btnClearToday"){state.todayList=[];return save();} if(t.id==="btnSaveVisit")return saveVisit(); if(t.id==="btnGps")return gpsCheckIn(); if(t.id==="btnExport")return exportData(); if(t.id==="btnTestReset"){state.todayList=[];save();alert("Week reset: today list cleared.");return;} if(t.id==="btnMarkClusterDone")return markClusterDone(); if(t.id==="btnExportKpi")return exportKpi(); if(t.id==="btnSaveSettings")return saveSettings(); if(t.id==="btnFactoryReset")return factoryReset();
 if(t.dataset.act==="up"){const i=Number(t.dataset.idx);if(i>0)[state.todayList[i-1],state.todayList[i]]=[state.todayList[i],state.todayList[i-1]];return save();}
 if(t.dataset.act==="down"){const i=Number(t.dataset.idx);if(i<state.todayList.length-1)[state.todayList[i+1],state.todayList[i]]=[state.todayList[i],state.todayList[i+1]];return save();}
 if(t.dataset.act==="remove"){const i=Number(t.dataset.idx);state.todayList.splice(i,1);return save();}
 if(t.dataset.act==="log"){byId("visitCustomer").value=t.dataset.name;setTab("visit");return;}
 if(t.dataset.act==="addToday"){const name=t.dataset.name;if(!state.todayList.includes(name))state.todayList.push(name);return save();}
 if(t.dataset.act==="openCustomer"){const name=t.dataset.name;const c=state.customers.find(x=>x.name===name);if(!c)return;const last=c.visitHistory?.[c.visitHistory.length-1];alert(`${c.name}\n\nKey Contact: ${c.keyContact||"—"}\nNext Action: ${c.nextAction||"—"}\nLast Visit: ${last?last.date+" • "+last.outcome:"—"}`);return;}
});
byId("customerSearch").addEventListener("input",renderCustomers);
byId("customerFilter").addEventListener("change",renderCustomers);
byId("reportPeriod").addEventListener("change",renderReport);
byId("reportRoute").addEventListener("change",renderReport);
byId("fileImport").addEventListener("change",(e)=>{const f=e.target.files?.[0]; if(f) importData(f); e.target.value="";});
renderAll();
